<?php
require_once APPPATH.'../vendor/autoload.php';
ob_start();
//var_dump($nombre);
$html = '<!DOCTYPE HTML "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Netscape * Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.50 -->
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Simple List</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
		<style type="text/css">

		.s373ff515{Font:9pt Arial;border:0px;text-align:left;vertical-align:top;white-space:nowrap;overflow:hidden;}
		.s38be7d72{Font:8pt Arial;border:0px;text-align:left;vertical-align:top;white-space:nowrap;overflow:hidden;}
		</style>

	</head>
	<body style="margin:0;">
		<div style="position: absolute; pointer-events: none; filter: alpha(Opacity=30); opacity: 0.3; -moz-opacity: 0.3; -khtml-opacity: 0.3; font-size: 100px; font-weight: bold; width: 1019px; margin-top: 285px; text-align: center; font-family: Arial; color: black; z-index: 9999; transform: rotate(-45deg);"></div>
		<table cellspacing="0" cellpadding="0" border="0" style="border-width:0px;width:979px;border-collapse:collapse;">
			<tr style="height:90px;">
				<td style="border:0px;height:90px;width:393px;"></td><td style="border:0px;height:90px;width:192px;"></td><td style="border:0px;height:90px;width:171px;"></td><td style="border:0px;height:90px;width:30px;"></td><td style="border:0px;height:90px;width:30px;"></td><td style="border:0px;height:90px;width:8px;"></td><td style="border:0px;height:90px;width:23px;"></td><td style="border:0px;height:90px;width:15px;"></td><td style="border:0px;height:90px;width:7px;"></td><td style="border:0px;height:90px;width:8px;"></td><td style="border:0px;height:90px;width:15px;"></td><td style="border:0px;height:90px;width:23px;"></td><td style="border:0px;height:90px;width:7px;"></td><td style="border:0px;height:90px;width:8px;"></td><td style="border:0px;height:90px;width:22px;"></td><td style="border:0px;height:90px;width:8px;"></td><td style="border:0px;height:90px;width:19px;"></td>
			</tr><tr style="height:8px;">
				<td style="border:0px;height:8px;width:393px;"></td><td style="border:0px;height:8px;width:192px;"></td><td style="border:0px;height:8px;width:171px;"></td><td style="border:0px;height:8px;width:30px;"></td><td style="border:0px;height:8px;width:30px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:23px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:7px;"></td><td class="s373ff515" colspan="5" style="max-width:61px;max-height:8px;white-space:nowrap;height:8px;width:61px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$Fecha.'</td><td style="border:0px;height:8px;width:22px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:19px;"></td>
			</tr><tr style="height:7px;">
				<td style="border:0px;height:7px;width:393px;"></td><td style="border:0px;height:7px;width:192px;"></td><td style="border:0px;height:7px;width:171px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:22px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:19px;"></td>
			</tr><tr style="height:8px;">
				<td style="border:0px;height:8px;width:393px;"></td><td style="border:0px;height:8px;width:192px;"></td><td style="border:0px;height:8px;width:171px;"></td><td style="border:0px;height:8px;width:30px;"></td><td class="s373ff515" colspan="3" style="max-width:61px;max-height:8px;white-space:nowrap;height:8px;width:61px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$Nombre.' '.$Apellido.'</td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:7px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:23px;"></td><td style="border:0px;height:8px;width:7px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:22px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:19px;"></td>
			</tr><tr style="height:7px;">
				<td style="border:0px;height:7px;width:393px;"></td><td style="border:0px;height:7px;width:192px;"></td><td style="border:0px;height:7px;width:171px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:22px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:19px;"></td>
			</tr><tr style="height:8px;">
				<td style="border:0px;height:8px;width:393px;"></td><td style="border:0px;height:8px;width:192px;"></td><td style="border:0px;height:8px;width:171px;"></td><td class="s373ff515" colspan="3" style="max-width:68px;max-height:8px;white-space:nowrap;height:8px;width:68px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$Direccion.'</td><td style="border:0px;height:8px;width:23px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:7px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:23px;"></td><td style="border:0px;height:8px;width:7px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:22px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:19px;"></td>
			</tr><tr style="height:7px;">
				<td style="border:0px;height:7px;width:393px;"></td><td style="border:0px;height:7px;width:192px;"></td><td style="border:0px;height:7px;width:171px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:22px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:19px;"></td>
			</tr><tr style="height:8px;">
				<td style="border:0px;height:8px;width:393px;"></td><td style="border:0px;height:8px;width:192px;"></td><td style="border:0px;height:8px;width:171px;"></td><td style="border:0px;height:8px;width:30px;"></td><td class="s373ff515" colspan="4" style="max-width:76px;max-height:8px;white-space:nowrap;height:8px;width:76px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$DUI.' - '.$NIT.'</td><td style="border:0px;height:8px;width:7px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:15px;"></td><td class="s373ff515" colspan="4" style="max-width:60px;max-height:8px;white-space:nowrap;height:8px;width:60px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$Telefono.'</td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:19px;"></td>
			</tr><tr style="height:60px;">
				<td style="border:0px;height:60px;width:393px;"></td><td style="border:0px;height:60px;width:192px;"></td><td style="border:0px;height:60px;width:171px;"></td><td style="border:0px;height:60px;width:30px;"></td><td style="border:0px;height:60px;width:30px;"></td><td style="border:0px;height:60px;width:8px;"></td><td style="border:0px;height:60px;width:23px;"></td><td style="border:0px;height:60px;width:15px;"></td><td style="border:0px;height:60px;width:7px;"></td><td style="border:0px;height:60px;width:8px;"></td><td style="border:0px;height:60px;width:15px;"></td><td style="border:0px;height:60px;width:23px;"></td><td style="border:0px;height:60px;width:7px;"></td><td style="border:0px;height:60px;width:8px;"></td><td style="border:0px;height:60px;width:22px;"></td><td style="border:0px;height:60px;width:8px;"></td><td style="border:0px;height:60px;width:19px;"></td>
			</tr><tr style="height:8px;">
				<td style="border:0px;height:8px;width:393px;"></td><td style="border:0px;height:8px;width:192px;"></td><td style="border:0px;height:8px;width:171px;"></td><td class="s373ff515" colspan="2" style="max-width:60px;max-height:8px;white-space:nowrap;height:8px;width:60px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$Descripcion.'</td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:23px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:7px;"></td><td style="border:0px;height:8px;width:8px;"></td><td class="s373ff515" colspan="2" style="max-width:38px;max-height:8px;white-space:nowrap;height:8px;width:38px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$PrecioUni.'</td><td class="s373ff515" colspan="3" style="max-width:37px;max-height:8px;white-space:nowrap;height:8px;width:37px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$PrecioUni.'</td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:19px;"></td>
			</tr><tr style="height:436px;">
				<td style="border:0px;height:436px;width:393px;"></td><td style="border:0px;height:436px;width:192px;"></td><td style="border:0px;height:436px;width:171px;"></td><td style="border:0px;height:436px;width:30px;"></td><td style="border:0px;height:436px;width:30px;"></td><td style="border:0px;height:436px;width:8px;"></td><td style="border:0px;height:436px;width:23px;"></td><td style="border:0px;height:436px;width:15px;"></td><td style="border:0px;height:436px;width:7px;"></td><td style="border:0px;height:436px;width:8px;"></td><td style="border:0px;height:436px;width:15px;"></td><td style="border:0px;height:436px;width:23px;"></td><td style="border:0px;height:436px;width:7px;"></td><td style="border:0px;height:436px;width:8px;"></td><td style="border:0px;height:436px;width:22px;"></td><td style="border:0px;height:436px;width:8px;"></td><td style="border:0px;height:436px;width:19px;"></td>
			</tr><tr style="height:8px;">
				<td style="border:0px;height:8px;width:393px;"></td><td style="border:0px;height:8px;width:192px;"></td><td style="border:0px;height:8px;width:171px;"></td><td style="border:0px;height:8px;width:30px;"></td><td style="border:0px;height:8px;width:30px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:23px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:7px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:23px;"></td><td class="s373ff515" colspan="4" style="max-width:45px;max-height:8px;white-space:nowrap;height:8px;width:45px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$PrecioUni.'</td><td style="border:0px;height:8px;width:19px;"></td>
			</tr><tr style="height:7px;">
				<td style="border:0px;height:7px;width:393px;"></td><td style="border:0px;height:7px;width:192px;"></td><td style="border:0px;height:7px;width:171px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:22px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:19px;"></td>
			</tr><tr style="height:8px;">
				<td style="border:0px;height:8px;width:393px;"></td><td style="border:0px;height:8px;width:192px;"></td><td style="border:0px;height:8px;width:171px;"></td><td style="border:0px;height:8px;width:30px;"></td><td style="border:0px;height:8px;width:30px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:23px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:7px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:23px;"></td><td class="s373ff515" colspan="4" style="max-width:45px;max-height:8px;white-space:nowrap;height:8px;width:45px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$ISR.'</td><td style="border:0px;height:8px;width:19px;"></td>
			</tr><tr style="height:7px;">
				<td style="border:0px;height:7px;width:393px;"></td><td style="border:0px;height:7px;width:192px;"></td><td style="border:0px;height:7px;width:171px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:30px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:15px;"></td><td style="border:0px;height:7px;width:23px;"></td><td style="border:0px;height:7px;width:7px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:22px;"></td><td style="border:0px;height:7px;width:8px;"></td><td style="border:0px;height:7px;width:19px;"></td>
			</tr><tr style="height:8px;">
				<td style="border:0px;height:8px;width:393px;"></td><td style="border:0px;height:8px;width:192px;"></td><td style="border:0px;height:8px;width:171px;"></td><td style="border:0px;height:8px;width:30px;"></td><td style="border:0px;height:8px;width:30px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:23px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:7px;"></td><td style="border:0px;height:8px;width:8px;"></td><td style="border:0px;height:8px;width:15px;"></td><td style="border:0px;height:8px;width:23px;"></td><td class="s373ff515" colspan="4" style="max-width:45px;max-height:8px;white-space:nowrap;height:8px;width:45px;overflow:hidden;text-overflow:clip;box-sizing:border-box;">'.$Total.'</td><td style="border:0px;height:8px;width:19px;"></td>
			</tr><tr style="height:3px;">
				<td style="border:0px;height:3px;width:393px;"></td><td style="border:0px;height:3px;width:192px;"></td><td style="border:0px;height:3px;width:171px;"></td><td style="border:0px;height:3px;width:30px;"></td><td style="border:0px;height:3px;width:30px;"></td><td style="border:0px;height:3px;width:8px;"></td><td style="border:0px;height:3px;width:23px;"></td><td style="border:0px;height:3px;width:15px;"></td><td style="border:0px;height:3px;width:7px;"></td><td style="border:0px;height:3px;width:8px;"></td><td style="border:0px;height:3px;width:15px;"></td><td style="border:0px;height:3px;width:23px;"></td><td style="border:0px;height:3px;width:7px;"></td><td style="border:0px;height:3px;width:8px;"></td><td style="border:0px;height:3px;width:22px;"></td><td style="border:0px;height:3px;width:8px;"></td><td style="border:0px;height:3px;width:19px;"></td>
			</tr><tr style="height:50px;">
				<td style="border:0px;height:50px;width:393px;"></td><td class="s38be7d72" style="white-space:nowrap;height:50px;width:192px;line-height:0;"></td><td style="border:0px;height:50px;width:171px;"></td><td style="border:0px;height:50px;width:30px;"></td><td style="border:0px;height:50px;width:30px;"></td><td style="border:0px;height:50px;width:8px;"></td><td style="border:0px;height:50px;width:23px;"></td><td style="border:0px;height:50px;width:15px;"></td><td style="border:0px;height:50px;width:7px;"></td><td style="border:0px;height:50px;width:8px;"></td><td style="border:0px;height:50px;width:15px;"></td><td style="border:0px;height:50px;width:23px;"></td><td style="border:0px;height:50px;width:7px;"></td><td style="border:0px;height:50px;width:8px;"></td><td style="border:0px;height:50px;width:22px;"></td><td style="border:0px;height:50px;width:8px;"></td><td style="border:0px;height:50px;width:19px;"></td>
			</tr><tr style="height:1px;">
				<td style="border:0px;height:1px;width:393px;"></td><td style="border:0px;height:1px;width:192px;"></td><td style="border:0px;height:1px;width:171px;"></td><td style="border:0px;height:1px;width:30px;"></td><td style="border:0px;height:1px;width:30px;"></td><td style="border:0px;height:1px;width:8px;"></td><td style="border:0px;height:1px;width:23px;"></td><td style="border:0px;height:1px;width:15px;"></td><td style="border:0px;height:1px;width:7px;"></td><td style="border:0px;height:1px;width:8px;"></td><td style="border:0px;height:1px;width:15px;"></td><td style="border:0px;height:1px;width:23px;"></td><td style="border:0px;height:1px;width:7px;"></td><td style="border:0px;height:1px;width:8px;"></td><td style="border:0px;height:1px;width:22px;"></td><td style="border:0px;height:1px;width:8px;"></td><td style="border:0px;height:1px;width:19px;"></td>
			</tr>
		</table><script type="text/javascript">
		</script><script type="text/javascript">
		</script></body>
</html>
';
$mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8','orientation' => 'L', 'margin_left' => '0','margin_right'=>'0','margin_top'=>'15','margin_bottom'=>'0','margin_header'=>'0','margin_footer'=>'0']);
$mpdf->WriteHTML($html);
//$mpdf->Output('nuevaFactura.pdf','D');
$mpdf->Output();
//echo $html;
?>
